POST http://localhost:8080/rest/register.do
Content-Type: application/x-www-form-urlencoded

orderNumber=1&amount=5&currency=10&returnUrl=http://testsuccess.com&failUrl=http://testfail.com&userName=admin&password=pass

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set('createdId', response.body.id);
});
%}

###

POST http://localhost:8080/rest/register.do
Content-Type: application/x-www-form-urlencoded

orderNumber=1&amount=5&currency=10&returnUrl=http://testsuccess.com&failUrl=http://testfail.com&userName=invalid_admin&password=invalid_pass

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 401, "Response status is not 401");
});
%}

###

POST http://localhost:8080/rest/reverse.do
Content-Type: application/x-www-form-urlencoded

id=1&userName=admin&password=pass


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/rest/deposit.do
Content-Type: application/x-www-form-urlencoded

id=1&amount=5&userName=admin&password=pass

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/rest/getOrderStatus.do
Content-Type: application/x-www-form-urlencoded

id=1&userName=admin&password=pass

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/rest/getOrderStatus.do
Content-Type: application/x-www-form-urlencoded

id=1&userName=another_admin&password=another_pass

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 403, "Response status is not 403");
});
%}